title: "Krzyhau's Blog"
description: "Rambling about tech, art, and everything in between."
author:
  name: "Krzyhau"
  email: "contact@krzyhau.pl"
  url: "https://krzyhau.pl/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Krzyhau"
year : "2025"
